### ISSUE TITLE
opcode "balance2" not highlighted

### ISSUE THREAD

**Issue by AsterixMusic** [csound/csound-vscode-plugin#18]
It seems balance2 is not highlighted.
I add a screenshot - Line 19

<img width="549" alt="Screenshot 2021-05-14 at 20 15 24" src="https://user-images.githubusercontent.com/68651266/118318928-5b35ac80-b4fa-11eb-98f0-c756d3553172.png">

**Comment by kunstmusik** [comment]
I synced the opcode list with Nate Whetsell's language-csound Atom package (Csound 6.15.0 opcode definitions).  This is now available in 0.3.1 version of the vscode plugin. Thanks for reporting!
