### ISSUE TITLE
"--port=10000" is missing from the csound.playArgs

### ISSUE THREAD

**Issue by michaelmariaott** [csound/csound-vscode-plugin#30]
By default the csound.playArgs only contain "-odac", which means the `ctrl + enter` command is not able to send any code to the running csound process. This is confusing for new users and should either be changed (add "--port=10000" to the default settings) or mentioned in the documentation.

**Comment by kunstmusik** [comment]
Thanks for noting this, I've added some information to the README for adding the port flag.
