### ISSUE TITLE
Please add syntax highlighting for .instr files

### ISSUE THREAD

**Issue by danishfurniture** [csound/csound-vscode-plugin#35]
Some csound code is written for instruments like the QuBit Nebulae. Files for that module have the extension ".instr". Could you please add that file extension to the type of files that will highlight csound syntax? Thank you!

**Comment by kunstmusik** [comment]
Thanks for requesting, I added .instr as a file type for ORC code and published 0.5.2 of the extension. It should show up on the marketplace shortly.

**Comment by danishfurniture** [comment]
Thanks Steven. It seems to work well! Much appreciated!
